### ISSUE TITLE
Image for read me

### ISSUE THREAD

**Issue by ghost** [samcarter8/tikzducks#1]
![duck_examples](https://user-images.githubusercontent.com/8226363/28834301-28980fac-76e2-11e7-91b5-cdb3d16c45a1.png)

**Comment by ghost** [comment]
![duck_examples](https://user-images.githubusercontent.com/8226363/28897479-36cb96ac-77e1-11e7-865f-2fcdd262ad03.png)

**Comment by ghost** [comment]
![duck_examples](https://user-images.githubusercontent.com/8226363/29253620-1c4ea2de-8082-11e7-800b-64df42ce6a66.png)

**Comment by ghost** [comment]
![duck_examples](https://user-images.githubusercontent.com/8226363/33049537-e71e9dd0-ce60-11e7-8b4c-7e1de0177f14.png)

**Comment by ghost** [comment]
![xmas](https://user-images.githubusercontent.com/8226363/43651585-1281b074-9743-11e8-97f5-bf70617738a5.png)
![aqua](https://user-images.githubusercontent.com/8226363/43651586-12a6c008-9743-11e8-99d2-5a66e7f5f1ee.png)
![pizza](https://user-images.githubusercontent.com/8226363/43651587-12c92daa-9743-11e8-83b5-7fd3a3ac19a3.png)
![ground](https://user-images.githubusercontent.com/8226363/43651589-12e84334-9743-11e8-9621-d5e6e53a0ca8.png)

**Comment by samcarter** [comment]
![screen shot 2018-10-25 at 10 56 07](https://user-images.githubusercontent.com/43832342/47489776-b3770700-d847-11e8-9b45-5178fb2bdf9c.png)

**Comment by samcarter** [comment]
![screen shot 2018-10-25 at 10 56 07](https://user-images.githubusercontent.com/43832342/47496794-37d18600-d858-11e8-9e6e-777ffee1acdc.png)
![screen shot 2018-10-25 at 11 21 02](https://user-images.githubusercontent.com/43832342/47496795-37d18600-d858-11e8-8c0c-20ea2d0a23cd.png)


![screen shot 2018-12-09 at 23 46 23](https://user-images.githubusercontent.com/43832342/49704004-3cd27500-fc0d-11e8-9002-319a8e71aca7.png)


![Screen Shot 2019-07-17 at 18 47 54](https://user-images.githubusercontent.com/43832342/61394501-84b42b80-a8c3-11e9-9540-c9c80e6b3b34.png)
