### ISSUE TITLE
Ducktor

### ISSUE THREAD

**Issue by lahvak** [samcarter8/tikzducks#19]
This awesome package is nevertheless missing a ducktor: perhaps with white coat and stethoscope.

**Comment by ghost** [comment]
Good idea - thanks for the suggestion! I'll see what I can do for the next release.

**Comment by ghost** [comment]
Sorry, that it took so much time, but here is the first draft

![test](https://user-images.githubusercontent.com/8226363/39408069-0149c296-4bd1-11e8-84c5-2f7cb7aeb260.png)

**Comment by ghost** [comment]
![test](https://user-images.githubusercontent.com/8226363/39409582-ec80a74e-4be9-11e8-8e8d-a3fa65bf4266.png)
