### ISSUE TITLE
Santa duck is missing

### ISSUE THREAD

**Issue by huftis** [samcarter8/tikzducks#2]
How about a Santa duck? Obviously, it needs a beard and/or a hat.
Perhaps take a look at the `santa` implementation in `tikzpeople`:
http://mirrors.ctan.org/graphics/pgf/contrib/tikzpeople/tikzpeople.pdf

And here’s a few million images for inspiration:
https://google.com/search?q=santa+duck&tbm=isch

**Comment by ghost** [comment]
@huftis I like this idea! I'll put it on my todo list.

**Comment by ghost** [comment]
@huftis The brand new Santa duck
![screen shot 2017-08-14 at 01 07 55](https://user-images.githubusercontent.com/8226363/29254050-0ed545e4-808d-11e7-8ab8-817d777bc102.png)

(beard may come later)
