### ISSUE TITLE
Monet and Surfer

### ISSUE THREAD

**Issue by malipivo** [samcarter8/tikzducks#22]
Good day, lovely work! There are URLs in README pointing to Monet and Surfer, but, at the moment, they are not among files in /duckpond/.

**Comment by samcarter** [comment]
Thanks for reporting!

**Comment by cereda** [comment]
@malipivo Hey! I know you from TeX.sx! Long time no see!

I hope you and your loved ones are well during these challenging times! Stay safe! :wink: 

Cheerio!

**Comment by malipivo** [comment]
@cereda Thank you, man!  The same wishes back to you: stay strong! Pablo
