### ISSUE TITLE
Tikzducks-generic file missing?

### ISSUE THREAD

**Issue by Leviathantheesper** [samcarter8/tikzducks#27]
Hi

I just installed this package but I haven't been able to compile any duck.
The issue occurs everytime I try to draw a duck. When I try to compile the following:

> \documentclass{standalone}
> \usepackage{tikzducks}
> \begin{document}
> \begin{tikzpicture}
> 	\duck
> \end{tikzpicture}	
> \end{document}

I get the error 

> ! I can't find file `tikzducks-generic'.
> ! Emergency stop. \input tikzducks-generic
> ! ==> Fatal error occurred, no output PDF file produced!
When I search tikzducks in my machine it seems I can't find the file 'tikzducks-generic.tex' so I thought if I downloaded the file the issue would be solved. The issue persists with the same error message but perhaps because I'm not sure about where should I put the file.

**Comment by samcarter** [comment]
Thanks for the report!

I'm having problems to reproduce the issue you report. Could you please tell me 
1. which tex distribution you use (texlive, miktex?)
2. which engine do you use to compile (pdflatex, xelatex, lualatex,...)

**Comment by joulev** [comment]
@Leviathantheesper ~~I suspect you installed the package manually, which can go wrong very easily if you are not familiar with the TDS. Please install the package with your TeX distribution’s package manager. For example on TeX Live~~

~~`$ sudo tlmgr install tikzducks`~~

This is [a MiKTeX issue](https://github.com/MiKTeX/miktex-packaging/issues/182) afaik.

**Comment by Leviathantheesper** [comment]
> Thanks for the report!
> 
> I'm having problems to reproduce the issue you report. Could you please tell me
> 
> 1. which tex distribution you use (texlive, miktex?)
> 2. which engine do you use to compile (pdflatex, xelatex, lualatex,...)

I'm using MiKTeX (I notice I didn't mention I use windows 10), and I'm trying to compile pdflatex.  It seems it's a MiKTeX issue, according to the link joulev posted.  Since the file can be downloaded I expected I would be able to fix it by pasting it in the appropiate location but I haven't figured out where is that.

Also it works correctly when I use overleaf so it's indeed something in my end (MiKTeX I suppose).

**Comment by samcarter** [comment]
@Leviathantheesper As a temporary workaround until this gets fixed in miktex, you can download https://github.com/samcarter/tikzducks/blob/master/tikzducks-generic.tex and place it in your working folder

**Comment by Leviathantheesper** [comment]
That works.

**Comment by samcarter** [comment]
Has been fixed by miktex https://github.com/MiKTeX/miktex-packaging/issues/182

**Comment by samcarter** [comment]
closing
