### ISSUE TITLE
Monochromatic ducks

### ISSUE THREAD

**Issue by cereda** [samcarter8/tikzducks#3]
I was wondering if it would be possible to make monochromatic ducks with a key instead of explicitly making them colourless. I know `xcolor` has an option to globally change the entire colourscheme to monochromatic, but I was thinking more along the lines of a local change.

Probably one for the TikZ experts. 😉

**Comment by ghost** [comment]
@cereda Thanks for your idea! It is certainly useful to create monochrome ducks, however I feel this should be handled with `tikz` weapons and not by the duck package itself. 

I propose to use 

```
\documentclass{article}

\usepackage{tikzducks}

\begin{document}
\begin{tikzpicture}
\selectcolormodel{gray}
\duck
\end{tikzpicture}
\end{document}
```

![screen shot 2017-08-05 at 12 43 15](https://user-images.githubusercontent.com/8226363/28994950-fe3c5252-79db-11e7-954d-74a920745ad0.png)
 
Of course I could make some key and use `\selectcolormodel{gray}` internally, but somehow I think this would open an never ending stream of things which should really be handled by `tikz` and not by the ducks. The same train of thoughts made me leave scaling etc. to be done by the tikz site.

What's your opinion about letting tikz handle this?

**Comment by cereda** [comment]
Great idea! I was unaware of `\selectcolormodel{gray}` and thought it would require some sort of advanced trickery! I suggest leaving the monochromatic option to the TikZ environment and not to the package itself. If possible, add a quick mention to this in the documentation, so TikZ newbies like myself will be able to get monochromatic ducks whenever possible. 😉 

Quack!

**Comment by ghost** [comment]
added monochrome customisation to documentation: https://github.com/samcarter8/tikzducks/commit/4b0b12b1716989f5b7ad9b4981c3460cb542b30c
