### ISSUE TITLE
Does not always work on TexpadTex

### ISSUE THREAD

**Issue by lkoehl** [samcarter8/tikzducks#31]
I just stumbled upon this awesome library and wanted to include it in my project. I tried to use it with just the lightsaber and everything works perfectly. Having just a lightsaber my duck looked a bit dull and I wanted to upgrade it with a Darth Vader helmet, which sadly doesn't work.

I am using TexpadTex for convenience reasons. Switching to other tex-distributions it of course works perfectly fine. I am now wondering why it doesn't always work on TexpadTex.

The error thrown is:
```
! Package pgfkeys Error: I do not know the key '/duck/darthvader', to which you passed 'black!30!gray', and I am going to ignore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.58          black!30!gray]
```

I am hoping to use the cute ducks with TexpadTex in the future 🐤

**Comment by samcarter** [comment]
I am not familiar with texpadtex, but one scenario which would cause such an error message would be an old version of the tikzducks package. Can you show your .log file to see which version you are using?

**Comment by lkoehl** [comment]
I can totally understand why, but thanks for looking into it. You can find the log [here](https://pastebin.com/Eeg4EJj5)

**Comment by samcarter** [comment]
Looks like an old version. Can you download http://mirrors.ctan.org/graphics/pgf/contrib/tikzducks.zip and put the files from there in the same folder as your .tex file?

**Comment by lkoehl** [comment]
That seems to fix the problem. No idea why its using an older version and I will have to take a deeper look into how I can get the newer versions. Thanks for the fast help!

**Comment by samcarter** [comment]
@lkoehl  You're welcome! And have fun with the ducks!

**Comment by samcarter** [comment]
From https://www.texpad.com/docs/tutorials/tex/typesetters/external/texlive-mactex it looks like you could install an up-to-date version of texlive/mactex and use it with texpad

**Comment by lkoehl** [comment]
Thanks. I think my students will like them too.

Of course I can use external typesetters with Texpad, but they doesn't come with the comfort of TexpadTex in Texpad.
Its always a struggle to get some packages to work.

Looking at [this link](https://www.texpad.com/docs/apps/typesetting/custom-packages) it should be possible to install and updates packages with tlmgr. I tried updating tikzducks but Darth Vader still doesn't work. I'm still an amateur with tex, but I read the author of a package needs to publish it to tlmgr. Is it possible that there is an outdated package listed in the store/database of tlmgr? And if so could you update it?

Otherwise I will just use the downloaded version of tikzducks and add it to my path so all projects can reference it.

**Comment by samcarter** [comment]
tlmgr is the updater for texlive and will only update the package until the end of the "year" you have installed. I'm not quite sure which texlive your texpad thingy is based on, but based on the package versions I'd say it is texlive2017 (on the other hand, format=latex 2021.3.29 seem much newer...).

So assuming texlive2017, tlmgr will only be able to update to the package versions as they were in early 2018, but darthvader needs at least version 0.6, which was released  in April 2018.
