### ISSUE TITLE
Broom duck doesn't work - PGF Keys error

### ISSUE THREAD

**Issue by hakmad** [samcarter8/tikzducks#35]
I have the following LaTeX code:

```tex
\documentclass{standalone}

\usepackage{tikz}
\usetikzlibrary{ducks}

\begin{document}

\begin{tikzpicture}
    \duck[broom]
\end{tikzpicture}

\end{document}
```

When compiling with `latexmk`, I recieve the following error:

```
! Package pgfkeys Error: I do not know the key '/pgf/broom' and I am going to ignore it. Perhaps you misspelled it.
```

The broom related accessories (e.g. `broomstick`, etc.) produce similar errors, but other accessories (e.g. `handbag`) work just fine. I'm not very good at LaTeX so this could just be me being stupid but I'm really not sure what's going on or how to diagnose this further.

By the way, this is really awesome!

Edit: fixed `documentclass`.

**Comment by samcarter** [comment]
Which version of the tikzducks package do you have? The broom was added in v1.6.

If you would show your .log file, I can look up the version number there.

(... and `\begin{standalone}` should be `\documentclass{standalone}`)

**Comment by hakmad** [comment]
I see, my bad. It looks like I'm still on version 1.5, so I'll look into how to upgrade my version of `tikzducks`. Sorry about that!

Also I corrected my example. Apologies again and thanks for your help!

**Comment by samcarter** [comment]
@hakmad  You're welcome! Have fun with the ducks!
