### ISSUE TITLE
Megaphone

### ISSUE THREAD

**Issue by maieul** [samcarter8/tikzducks#37]
Should it be possible to have a megaphone as accesories ?

**Comment by samcarter** [comment]
Thank you for the suggestion!

![document-1](https://github.com/user-attachments/assets/3e8be7f0-d488-4125-bf0a-8a66cc369421)

**Comment by maieul** [comment]
Thamk you very much. I suppose it will be released soon on CTAN ?

**Comment by samcarter** [comment]
v1.9 is on its way to ctan
